defaults:
  run:
    working-directory: ./studio-android/LightNovelLibrary
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Set up Android emulator, build, test and coverage reports
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 21
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew assembleAlpha testAlphaDebugUnitTest connectedAlphaDebugAndroidTest
        working-directory: ./studio-android/LightNovelLibrary
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android-ci.yml
